### PR TITLE
bump version to 3.0.2

### PR DESCRIPTION
**Pull request by janjagusch**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by JanJaguschQC** [comment]
@conda-forge-admin, please rerender

**Comment by consideRatio** [comment]
Thanks for working to get this released @janjagusch!

For my understanding, what motivated b3578c7?

**Comment by janjagusch** [comment]
> Thanks for working to get this released @janjagusch!
> 
> For my understanding, what motivated [b3578c7](https://github.com/conda-forge/jupyter-server-proxy-feedstock/commit/b3578c79f3ecaad9c611e8b88435cb09316ec1f7)?

The original PyPI url wasn't working for me, so I tried to make it work using a GitHub url. @xhochy and I then found out that the PyPI url to the 3.0.0 release is different from the 1.6.0 release (`_`instead of `-`). So now I've reverted it back to and fixed the PyPI url. Still, I would probably recommend to re-release the tag with the same url structure. :)

**Comment by consideRatio** [comment]
> The original PyPI url wasn't working for me, so I tried to make it work using a GitHub url. @xhochy and I then found out that the PyPI url to the 3.0.0 release is different from the 1.6.0 release (_ instead of -). So now I've reverted it back to and fixed the PyPI url.

Ooohh I bet this wasn't intentional and a consequence of a change in our automation in https://github.com/jupyterhub/jupyter-server-proxy.

> Still, I would probably recommend to re-release the tag with the same url structure. :)

Sounds sensible to me!

**Comment by consideRatio** [comment]
I tracked down the change to this commit: https://github.com/jupyterhub/jupyter-server-proxy/commit/0fa76aabd2d77203606dbcd5c88cb7aa849fb6d9

What do you think about updating the name to use `-` instead of `_` and then cutting 3.0.1?

**Comment by janjagusch** [comment]
> I tracked down the change to this commit: [jupyterhub/jupyter-server-proxy@0fa76aa](https://github.com/jupyterhub/jupyter-server-proxy/commit/0fa76aabd2d77203606dbcd5c88cb7aa849fb6d9)
> 
> What do you think about updating the name to use `-` instead of `_` and then cutting 3.0.1?

> What do you think about updating the name to use `-` instead of `_` and then cutting 3.0.1?

Sounds good to me, I also went ahead and open an issue on the other end https://github.com/jupyterhub/jupyter-server-proxy/issues/258.

**Comment by janjagusch** [comment]
@consideRatio, thanks for merging https://github.com/jupyterhub/jupyter-server-proxy/pull/259

Could you maybe release a 3.0.1 tag (or re-release 3.0.0, I have no preference), so we can try and see what happens here in the feedstock? :)

**Comment by consideRatio** [comment]
@janjagusch done!

**Comment by janjagusch** [comment]
> @janjagusch done!

File download is working now but the build doesn't quite succeed yet. We'll get there, though. :)

**Comment by xhochy** [comment]
Looks like we don't have all necessary files in the `sdist`.

**Comment by janjagusch** [comment]
@xhochy is right. the `jupyterlab-server-proxy` directory is missing in the sdist.

```
pkg_json = json.loads((HERE / "jupyterlab-server-proxy" / "package.json").read_bytes())
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/mj/2sx68gpn1bldjjpwtbqs8gfr0000gn/T/pip-req-build-24c69sj2/jupyterlab-server-proxy/package.json'
    Preparing wheel metadata ... error
```

**Comment by xhochy** [comment]
https://github.com/jupyterhub/jupyter-server-proxy/pull/260 fixes this locally.

**Comment by consideRatio** [comment]
@janjagusch @xhochy you absolute heroes! Thank you :tada: :heart:!

3.0.2 is released with the patch by @xhochy now!

**Comment by consideRatio** [comment]
image

WIEEE!!!

**Review by consideRatio — APPROVED** [review]

**Comment by janjagusch** [comment]
@consideRatio, forgot to remove the draft status. feel free to merge. :)

**Comment by consideRatio** [comment]
:tada: :heart: thanks for your thorough work @janjagusch and @xhochy!

**Pull request merged**
