### PR TITLE
Bump version from 1.3.0 to 1.3.1

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
Haha, terrible timing from me. Looks like I got leapfrogged.

**Comment by xhochy** [comment]
Thanks for making the PR, we have a bot that triggers these, so normally manual ones aren't needed. Weird that there was none for 1.3.1.

**Comment by jakirkham** [comment]
> Weird that there was none for 1.3.1.

cc @beckermr, in case you have any ideas. No worries if not 😉

**Comment by beckermr** [comment]
Yeah. I’ll look.

**Comment by beckermr** [comment]
Let’s make issues in regro/cf-scripts for these

**Comment by beckermr** [comment]
the bot did work once here: https://github.com/conda-forge/jupyter-server-proxy-feedstock/pull/11

**Comment by beckermr** [comment]
I am looking at the logs. The bot found 1.3.1 but I cannot find a log where it actually attempted the upgrade. I don't think we'll get to the bottom of this one.

**Pull request closed without merging**
